apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: discord-voice-logger
  name: discord-voice-logger
  labels:
    app: discord-voice-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-voice-logger
  template:
    metadata:
      labels:
        app: discord-voice-logger
    spec:
      containers:
      - name: bot
        image: ghcr.io/schwarztrinker/discord-voice-logger/bot:latest
        env:
        - name: CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: CHANNEL_ID
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: BOT_TOKEN
        - name: VOICE_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: VOICE_CHANNEL_ID